### ISSUE TITLE
Issue on email validation

### ISSUE THREAD

**Issue by apalumbo** [aiji42/zod-i18n#10]
We had some issues when validating emails it seems that the translated values are not interpolated, taking a look at the code it seems to me that some other kind of interpolation was expected or maybe it is just a bug.
The `t` function is not invoked maybe is an issue with the template string.
If you can confirm it, I could submit a fix asap with a PR

https://github.com/aiji42/zod-i18n/blob/63b988a953beea1c37fc5650b29503c5e985eef2/packages/core/src/index.ts#L97

**Comment by kevin-courbet** [comment]
Not sure if this is related / if this problem extends to more than just emails, but I'm getting these:
<img width="475" alt="image" src="https://user-images.githubusercontent.com/25525940/206814935-7547557c-4b9b-4be8-ba51-19b889390746.png">

With my zod.json taken from the original one eg:
```json
"invalid_string": {
      "email": "Invalid {{validation}}"
},
"errors":{
    "invalid_type": "Expected {{expected}}, received {{received}}"
}
```

**Comment by kevin-courbet** [comment]
Okay, that was a relatively easy fix, will push a PR in the following mins

**Comment by aiji42** [comment]
`t(...)` is not a type. This is i18next's nesting notation.
https://www.i18next.com/translation-function/nesting

`skipOnVariables: false` If you forget this setting, you will not be able to convert correctly.

If you are using `next-i18next`, please refer here.
https://github.com/aiji42/zod-i18n/blob/main/examples/with-next-i18next/README.md#3-project-setup

If you want to use `i18next` directly, here it is.
https://github.com/aiji42/zod-i18n#how-to-use
