### ISSUE TITLE
Zod literal message translation error

### ISSUE THREAD

**Issue by Gludek** [aiji42/zod-i18n#103]
Hi,
I'm trying to use zod, zod-i18n, react and formik, but when having  object like
```
...
fieldName: z.literal("nie"),
...
```
The error adds `&quot;` before and after the literal value.
In case of english it results in `Invalid literal value, expected &quot;nie&quot;`
Same when I checked in polish, and spanish.

**Comment by aiji42** [comment]
https://www.i18next.com/translation-function/interpolation#unescape

Put `-` to the variable portion of the translation data.
