### ISSUE TITLE
Zod error translate prints null on express

### ISSUE THREAD

**Issue by FranAM1** [aiji42/zod-i18n#125]
When I initialize setErrorMap with zodI18nMap make all the error messages to null. It works fine without the translation.
![image](https://user-images.githubusercontent.com/91600940/236668505-84804c8a-30e0-43c8-bcab-336d32ea8468.png)
![image](https://user-images.githubusercontent.com/91600940/236668548-63bb48be-034f-4287-ac9e-c4cc9c53afcd.png)

I import the i18n configuration to my index.js 

**i18n,js**
```js
import i18next from "i18next";
import { z } from "zod";
import { zodI18nMap } from "zod-i18n-map";
// Import your language translation files
import translation from "zod-i18n-map/locales/es/zod.json" assert { type: "json" };

// lng and resources key depend on your locale.

i18next.init({
    lng: "es",
    resources: {
      es: { zod: translation },
    },
});
z.setErrorMap(zodI18nMap);  
```

**index.js**
``` js
import app from './app.js'
import { sequelize } from './db/db.js'
import { createRoles } from './seeders/roles.seeder.js'
import { createUsers } from './seeders/users.seeder.js'
import dotenv from 'dotenv'
dotenv.config()
import './utils/i18n.js'

const PORT = process.env.SERVER_PORT || 3000

async function main() {
    try{
        // false = no elimina la base de datos | true = elimina la base de datos
        await sequelize.sync({force: true}) 
        await createRoles()
        await createUsers()
        app.listen(PORT)
        console.log(`Server is running on http://localhost:${PORT}`)
    }catch(error){
        "Error iniciar servidor: " + error
    }
}

main()
```

**Comment by hmnd** [comment]
Did you figure this out by any chance?

**Comment by FranAM1** [comment]
I still haven’t figured it out so I decided to leave the error messages in English for now

**Comment by hmnd** [comment]
@FranAM1 I think I just figured it out! Try to replace `zodI18nMap` with  `makeZodI18nMap({ t: i18next.t })`

**Comment by FranAM1** [comment]
IT WORKED, THANK YOU
![image](https://github.com/aiji42/zod-i18n/assets/91600940/fa474f13-1b52-4693-851f-926652ed432f)

**Comment by FadiAboMsalam** [comment]
@hmnd  you are life saver I love you bro 🎉

**Comment by verheyenkoen** [comment]
> @FranAM1 I think I just figured it out! Try to replace `zodI18nMap` with `makeZodI18nMap({ t: i18next.t })`

Life saver! Thanks!

**Comment by Sleepful** [comment]
this should be shown in the README!

**Comment by flofleche** [comment]
> this should be shown in the README!

Definitively missing in the README, I've wasted almost an entire day trying to figure out why translated messages were not working on SSR validation while in Client Side it was perfectly fine ( I'm using `React Router V7 / Remix` along with `Tanstack Form V1`).

With this simple bit of code switch from @hmnd's answer, it worked like a charm :
```js
z.setErrorMap(makeZodI18nMap({ t: i18next.t }))
```

Thx again for this trick !
