### ISSUE TITLE
Change the project to a monorepo

### ISSUE THREAD

**Issue by aiji42** [aiji42/zod-i18n#33]
Split the package into core logic and translation files so that each is released independently.

**Comment by ismailajizou** [comment]
That's a good idea, that way we can separate the example app from the package and make a docs website, and I am not sure if possible but another feature would be to make the developer decide which translations they want (for example download only the translation files of the locales you want to use).

**Comment by aiji42** [comment]
Thanks for your feedback. 

> for example download only the translation files of the locales you want to use

This is indeed true.
Although it is not feasible to publish each language's translation data as separated npm packages due to the large number (e.g. @zod-i18n/en, @zod-i18n/en, @zod-i18n/ar..., etc.), it may be possible to solve this problem by having people copy and paste the data themselves.
The tradeoff is the lack of version control and the fact that it is slightly more complicated for the user, so the decision should be made carefully.

**Comment by lSelectral** [comment]
As mentioned on [this issue](https://github.com/aiji42/zod-i18n/issues/45),
we can allow user to download which locales he/she wants.
