### ISSUE TITLE
How to use with zod's .regex()

### ISSUE THREAD

**Issue by asherccohen** [aiji42/zod-i18n#65]
Hi, great work!

I'd like to understand how to use custom errors on a per-base case like the one below:

I have the current setup:
```

import { createIntl, intlResources } from "services-shared";

import { FC } from "react";
import { I18nextProvider } from "react-i18next";
import { z } from "zod";
import { makeZodI18nMap } from "zod-i18n-map";
import zodDeTranslation from "zod-i18n-map/locales/de/zod.json";
import zodEnTranslation from "zod-i18n-map/locales/en/zod.json";
import zodFrTranslation from "zod-i18n-map/locales/fr/zod.json";
import zodItTranslation from "zod-i18n-map/locales/it/zod.json";

import de from "./locales/de/translation.json";
import en from "./locales/en/translation.json";
import fr from "./locales/fr/translation.json";
import it from "./locales/it/translation.json";

const resources = {
  en: {
    translation: mergeDeepRight(intlResources.en, en),
    zod: zodEnTranslation,
   },
  fr: {
    translation: mergeDeepRight(intlResources.fr, fr),
    zod: zodFrTranslation,
  },
  de: {
    translation: mergeDeepRight(intlResources.de, de),
    zod: mergeDeepRight(zodDeTranslation, {}),
  },
  it: {
    translation: mergeDeepRight(intlResources.it, it),
    zod: zodItTranslation,
  },
};

// our way to abstract away initializing i18n
export const i18n = createIntl({
  resources,
  debug: false,
  ns: ["translation", "zod"],
});

//BTW: I noticed that I must overwrite t, or all messages will come back as undefined
z.setErrorMap(makeZodI18nMap({ t: i18n.t, ns: ["translation", "zod"] }));

export const IntlProvider = ({
  children,
}) => {
  return <I18nextProvider i18n={i18n}>{children}</I18nextProvider>;
};

export default IntlProvider;

```

Then in a form I have to use .refine which is not great for re-implementing eg .regex:

```
export const consultationSchema = z.object({
  clientParticipants: z
    .string()
    .min(3)
    // .regex(CLIENT_PARTICIPANT_REGEX)
    //AC: At the moment we have to use this trick and move the regex in a custom validator
    .refine(
      (val) => {
        return val.match(CLIENT_PARTICIPANT_REGEX);
      },
      {
        params: { i18n: "errors.can-only-contain-alphanumeric-values" },
      }
    ),
  clientParticipantsName: z.string().min(3),
});

```

Is there a cleaner way to do this?

**Comment by aiji42** [comment]
Unfortunately, in your case, there is no other way but to use refile at this time.
This is the case not only with regex, but with all validating functions that give a custom message as the second argument.

This is because zod itself does not have such extensibility. **So this library can only translate the default error messages.**
Please wait for further updates on the zod side, which should make this library even more useful.

**Comment by asherccohen** [comment]
Thank you.
I understand, at least I know I'm not doing something wrong.

I read there's suggestion to enhance zod for intl, I'll track those issues on their GitHub.

Would be good to have a warning about the limitations of the library in the readme.

Guidance on the gotchas of the custom t function is useful too.
I had to debug source code to realize that the global i18next.t you're using internally was returning undefined 😂.

**Comment by jakewtaylor** [comment]
+1 for adding some docs around this - it's a shame we have to reimplement things such as `.regex`/`.min`/`.max` to use a custom key. 

In my case, I don't want to translate _every_ instance of `min`/`max`, just add a custom message for a specific instance (e.g. `"Length must be between 30 seconds and 5 minutes!"` for `.min(30).max(300)`)
