### ISSUE TITLE
Plurals

### ISSUE THREAD

**Issue by jezikk** [aiji42/zod-i18n#70]
Hi,

would be possible to support [plurals](https://www.i18next.com/translation-function/plurals)? I don't know If it is possible, but if so, it would be very useful for some languages.

Thank you,
Michal

**Comment by aiji42** [comment]
@jezikk thanks for the idea.
Can you clarify the use case a bit more? I find it personally interesting.

**Comment by jezikk** [comment]
Actually I use Zod with react-form-hook library. All errors are therefore presented directly to users.

In the default Zod error map for English is for example the following translation:
{code:json}
{
"array": {
        "exact": "Array must contain exactly {{maximum}} element(s)"
      },
}
{code}

If I want to express the same translation in Czech (and many other languages), I should have correctly the following:
{code:json}
{
"array": {
        "exact_one": "Seznam musí obsahovat přesně {{maximum}} položku",
        "exact_two": "Seznam musí obsahovat přesně {{maximum}} položky",
        "exact_three": "Seznam musí obsahovat přesně {{maximum}} položky",
        "exact_four": "Seznam musí obsahovat přesně {{maximum}} položky",
        "exact_other": "Seznam musí obsahovat přesně {{maximum}} položek"
      },
}
{code}

**Comment by aiji42** [comment]
Okay, it looks like I can support plurals by passing the maximum and minimum as counts to the translation function. I will start working on this development as soon as possible.

**Comment by aiji42** [comment]
It's done!
Update to the latest version and use it.

https://github.com/aiji42/zod-i18n#plurals

**Comment by aiji42** [comment]
@jezikk If you would be so kind, I would be very happy if you could add the Czech translation files.

**Comment by jezikk** [comment]
I will do it later using PR.
